### ISSUE TITLE
PHP 8.4 support?

### ISSUE THREAD

**Issue by rotdrop** [php-decimal/extension#88]
Thank you for your nice piece of software!

I am trying to compile from source on Ubuntue 25 (plucky) with php 8.4.5. After running phpize and configure I try to compile and then I run in to the error below. As it complains about a `zval *` vs. a `zend_object *` pointer I would assume that something the extension API of PHP has been changed.

```
heinecj@nbfbmcjh:~/projects/php/ext-decimal$ make 
/bin/bash /home/heinecj/projects/php/ext-decimal/libtool --tag=CC --mode=compile cc -I. -I/home/heinecj/projects/php/ext-decimal -I/usr/include/php/20240924 -I/usr/include/php/20240924/main -I/usr/include/php/20240924/TSRM -I/usr/include/php/20240924/Zend -I/usr/include/php/20240924/ext -I/usr/include/php/20240924/ext/date/lib -I/usr/include/x86_64-linux-gnu  -DHAVE_CONFIG_H  -g -O2 -D_GNU_SOURCE   -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /home/heinecj/projects/php/ext-decimal/src/compare.c -o src/compare.lo  -MMD -MF src/compare.dep -MT src/compare.lo
libtool: compile:  cc -I. -I/home/heinecj/projects/php/ext-decimal -I/usr/include/php/20240924 -I/usr/include/php/20240924/main -I/usr/include/php/20240924/TSRM -I/usr/include/php/20240924/Zend -I/usr/include/php/20240924/ext -I/usr/include/php/20240924/ext/date/lib -I/usr/include/x86_64-linux-gnu -DHAVE_CONFIG_H -g -O2 -D_GNU_SOURCE -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /home/heinecj/projects/php/ext-decimal/src/compare.c -MMD -MF src/compare.dep -MT src/compare.lo  -fPIC -DPIC -o src/.libs/compare.o
/home/heinecj/projects/php/ext-decimal/src/compare.c: In function 'php_decimal_compare_invoke':
/home/heinecj/projects/php/ext-decimal/src/compare.c:261:36: error: passing argument 1 of 'zend_call_method_with_1_params' from incompatible pointer type [-Wincompatible-pointer-types]
  261 |     zend_call_method_with_1_params((zval *) obj, Z_OBJCE_P(obj), NULL, "compareto", &cmp, (zval *) op2);
      |                                    ^~~~~~~~~~~~
      |                                    |
      |                                    zval * {aka struct _zval_struct *}
In file included from /home/heinecj/projects/php/ext-decimal/src/compare.c:24:
/usr/include/php/20240924/Zend/zend_interfaces.h:49:77: note: expected 'zend_object *' {aka 'struct _zend_object *'} but argument is of type 'zval *' {aka 'struct _zval_struct *'}
   49 | static zend_always_inline zval* zend_call_method_with_1_params(zend_object *object, zend_class_entry *obj_ce,
      |                                                                ~~~~~~~~~~~~~^~~~~~
make: *** [Makefile:210: src/compare.lo] Fehler 1
```

**Comment by rtheunissen** [comment]
I'll look into this ASAP, thank you for reporting.

**Comment by ndossche** [comment]
A lot more is needed (even parameter parsing using legacy Z_PARAM_STRICT_LONG breaks), it seems this extension in the current state cannot work with PHP 8.0 or higher.
I'd propose requiring PHP 8.0 for the next ext-decimal release at a minimum. I could help bring this to PHP 8.0 and higher, but only if I get a guarantee that this will result in a new release.
Edit: ah I see you're supposed to use branch 1.x, even though github defaults to master...

**Comment by rtheunissen** [comment]
Resolved in v2.0.0 — PHP 8.2, 8.3, and 8.4 are fully supported.
