### ISSUE TITLE
[1.5.1] is not compatible with PHP 7.x

### ISSUE THREAD

**Issue by remicollet** [php-decimal/extension#91]
package.xml states 7.0.0 is the minimal supported version
composer.json is missing

Build with 7.4
```
/builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c:2763:45: error: assignment to 'zend_object_get_properties_for_t' {aka 'struct _zend_array * (*)(struct _zval_struct *, enum _zend_prop_purpose)'} from incompatible pointer type 'HashTable * (*)(zend_object *, zend_prop_purpose)' {aka 'struct _zend_array * (*)(struct _zend_object *, enum _zend_prop_purpose)'} [-Wincompatible-pointer-types]
 2763 |     php_decimal_handlers.get_properties_for = php_decimal_get_properties_for;
      |                                             ^
/builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c:1803:19: note: 'php_decimal_get_properties_for' declared here
 1803 | static HashTable *php_decimal_get_properties_for(zend_object *obj, zend_prop_purpose purpose)
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/php/Zend/zend.h:355,
                 from /usr/include/php/main/php.h:33,
                 from /builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.h:40,
                 from /builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c:27:
/usr/include/php/Zend/zend_object_handlers.h:117:23: note: 'zend_object_get_properties_for_t' declared here
  117 | typedef zend_array *(*zend_object_get_properties_for_t)(zval *object, zend_prop_purpose purpose);
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/php/main/php_ini.h:22,
                 from /usr/include/php/main/fopen_wrappers.h:24,
                 from /usr/include/php/main/php.h:435:
/builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c: At top level:
/usr/include/php/Zend/zend_ini.h:98:73: warning: 'ini_entries' defined but not used [-Wunused-const-variable=]
   98 | #define ZEND_INI_BEGIN()                static const zend_ini_entry_def ini_entries[] = {
      |                                                                         ^~~~~~~~~~~
/usr/include/php/main/php_ini.h:54:33: note: in expansion of macro 'ZEND_INI_BEGIN'
   54 | #define PHP_INI_BEGIN           ZEND_INI_BEGIN
      |                                 ^~~~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c:2812:1: note: in expansion of macro 'PHP_INI_BEGIN'
 2812 | PHP_INI_BEGIN()
      | ^~~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c:444:13: warning: 'php_decimal_free' defined but not used [-Wunused-function]
  444 | static void php_decimal_free(php_decimal_t *obj)
      |             ^~~~~~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c:58:13: warning: 'php_decimal_print' defined but not used [-Wunused-function]
   58 | static void php_decimal_print(php_decimal_t *obj)
      |             ^~~~~~~~~~~~~~~~~
/builddir/build/BUILD/php-pecl-decimal-1.5.1-build/ext-decimal-1.5.1/php_decimal.c:47:13: warning: 'php_decimal_print_mpd' defined but not used [-Wunused-function]
   47 | static void php_decimal_print_mpd(mpd_t *mpd)
      |             ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:192: php_decimal.lo] Error 1

```

Building on another distro where -Wincompatible-pointer-types is not an error, build passes but test suite raise segfault

```
TEST 1/55 [tests/php7/cast.phpt]
========DIFF========
001+ Termsig=11
001- A Integer overflow
002- B Floating point underflow
003- C Floating point underflow
004- D Converting NaN or Inf to integer is not defined
005- E Converting NaN or Inf to integer is not defined
006- F Converting NaN or Inf to integer is not defined
========DONE========
FAIL Decimal cast to string, bool, int, float [tests/php7/cast.phpt] 

TEST 2/55 [tests/php7/clone.phpt]
========DIFF========
001+ Termsig=11
001- object(Decimal\Decimal)#1 (2) {
002-   ["value"]=>
003-   string(5) "1.234"
004-   ["precision"]=>
005-   int(16)
006- }
007- object(Decimal\Decimal)#2 (2) {
008-   ["value"]=>
009-   string(5) "1.234"
010-   ["precision"]=>
011-   int(16)
012- }
========DONE========
FAIL Decimal clone [tests/php7/clone.phpt] 

TEST 13/55 [tests/php7/methods/copy.phpt]
========DIFF========
001+ Termsig=11
001- object(Decimal\Decimal)#1 (2) {
002-   ["value"]=>
003-   string(3) "123"
004-   ["precision"]=>
005-   int(32)
006- }
007- object(Decimal\Decimal)#2 (2) {
008-   ["value"]=>
009-   string(3) "123"
010-   ["precision"]=>
011-   int(32)
012- }
========DONE========
FAIL Decimal::copy [tests/php7/methods/copy.phpt] 

TEST 48/55 [tests/php7/operators.phpt]
========DIFF========
001+ Termsig=11
001- object(Decimal\Decimal)#2 (2) {
002-   ["value"]=>
003-   string(4) "2E+8"
004-   ["precision"]=>
005-   int(12)
006- }
007- object(Decimal\Decimal)#1 (2) {
008-   ["value"]=>
009-   string(4) "1E+8"
010-   ["precision"]=>
011-   int(12)
012- }
013- int(0)
========DONE========
FAIL Decimal operators [tests/php7/operators.phpt] 

TEST 51/55 [tests/php7/serialize.phpt]
========DIFF========
004+   string(19) "00E+140258459074591"
004-   string(13) "1.2345678E+12"
006+   int(1)
006-   int(42)
========DONE========
FAIL Decimal serialize/unserialize [tests/php7/serialize.phpt] 

```

**Comment by zlodes** [comment]
It seems we need to drop that from ext metadata. 

I'm 100% sure we don't need to add a legacy PHP support.
PHP 7.4 reached End-of-Life (EOL) on November 28, 2022

**Comment by rtheunissen** [comment]
Fixed in v1.5.3 — the get_properties_for handler now uses the correct signature for PHP 7.x vs 8.0+.
